spring.application.name=JobApp
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=diwakarkumar9507@gmail.com
spring.mail.password=qhkupifxfenmmgbo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true